### ISSUE TITLE
Can we execute transaction in flurre server from react UI? 

### ISSUE THREAD

**Issue by Syed-Kashan-Adil** [fluree/js-react-wrapper#2]

**Comment by Syed-Kashan-Adil** [comment]
Hi @jakep36! I have seen you pushed some code regarding flurre transaction. Please let me know when it will be available in react wrapper?

**Comment by Tr3yb0** [comment]
Hi @Syed-Kashan-Adil! This question is better served by being asked in our [Slack channel](https://flureedb.slack.com) as opposed to as a GitHub issue. Would you mind re-posting it there?
